const handlers = [
	require('./null/nullHandler.js'),
	require('./undefined/undefinedHandler.js'),
	require('./Date/DateHandler.js'),
	require('./Error/ErrorHandler.js'),
	require('./RegExp/RegExpHandler.js'),
	require('./Promise/PromiseHandler.js'),
	require('./BigInt/BigIntHandler.js'),
	require('./Function/FunctionHandler.js'),
	require('./Symbol/SymbolHandler.js'),
	require('./String/StringHandler.js'),
	require('./Number/NumberHandler.js'),
	require('./Boolean/BooleanHandler.js'),
	require('./arguments/argumentsHandler.js'),
	require('./Array/ArrayHandler.js'),
	require('./TypedArray/TypedArrayHandler.js'),
	require('./WeakMap/WeakMapHandler.js'),
	require('./Map/MapHandler.js'),
	weaksetHandler,
	setHandler,
	require('./URL/URLHandler.js'),
	urlSearchParamsHandler,
	require('./Object/ObjectHandler.js'),
];

module.exports = handlers;
